services:
  db:
    image: mysql:lts
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=azki_reservation
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    networks:
      - reservation-net
    healthcheck:
      test: [ "CMD", "mysql", "-u", "root", "-proot", "--execute", "SHOW DATABASES;" ]
      interval: 3s
      retries: 5
      timeout: 5s

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - reservation-net

networks:
  reservation-net:
    driver: bridge